import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
const brandDir = path.join(rootDir, 'assets', 'brand');
const sourceSvgPath = path.join(brandDir, 'icon.svg');
const generatedModulePath = path.join(rootDir, 'src', 'ui', 'brand-assets.js');

function createIco(images) {
  const headerSize = 6;
  const entrySize = 16;
  const header = Buffer.alloc(headerSize);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);

  const entries = Buffer.alloc(entrySize * images.length);
  let offset = headerSize + entries.length;

  images.forEach(({ size, buffer }, index) => {
    const base = index * entrySize;
    entries.writeUInt8(size >= 256 ? 0 : size, base);
    entries.writeUInt8(size >= 256 ? 0 : size, base + 1);
    entries.writeUInt8(0, base + 2);
    entries.writeUInt8(0, base + 3);
    entries.writeUInt16LE(1, base + 4);
    entries.writeUInt16LE(32, base + 6);
    entries.writeUInt32LE(buffer.length, base + 8);
    entries.writeUInt32LE(offset, base + 12);
    offset += buffer.length;
  });

  return Buffer.concat([header, entries, ...images.map((image) => image.buffer)]);
}

async function renderPng(svg, size) {
  return await sharp(svg)
    .resize(size, size, { fit: 'contain' })
    .png({ compressionLevel: 9, adaptiveFiltering: true })
    .toBuffer();
}

export async function generateIcons() {
  const svg = await fs.readFile(sourceSvgPath, 'utf8');
  const svgBuffer = Buffer.from(svg);

  const icon192 = await renderPng(svgBuffer, 192);
  const icon512 = await renderPng(svgBuffer, 512);
  const icoImages = await Promise.all(
    [16, 32, 48].map(async (size) => ({ size, buffer: await renderPng(svgBuffer, size) }))
  );
  const favicon = createIco(icoImages);

  await fs.mkdir(brandDir, { recursive: true });
  await fs.writeFile(path.join(brandDir, 'icon-192.png'), icon192);
  await fs.writeFile(path.join(brandDir, 'icon-512.png'), icon512);
  await fs.writeFile(path.join(brandDir, 'favicon.ico'), favicon);

  const module = `// Generated by scripts/generate-icons.js. Do not edit by hand.
export const ICON_SVG = ${JSON.stringify(svg.trim())};
export const ICON_192_PNG_BASE64 = '${icon192.toString('base64')}';
export const ICON_512_PNG_BASE64 = '${icon512.toString('base64')}';
export const FAVICON_ICO_BASE64 = '${favicon.toString('base64')}';
`;
  await fs.writeFile(generatedModulePath, module);
  console.log('Generated brand icons');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  generateIcons().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
